/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { SolarTerm, MusicPreset } from './types';

export const SOLAR_TERMS: SolarTerm[] = [
  {
    id: 1,
    name: '立春',
    pinyin: 'Lìchūn',
    english: 'Beginning of Spring',
    season: 'spring',
    longitude: 315,
    dateRange: '2月3日 - 2月5日',
    meaning: '春季开始，大地回暖，万物渐次苏醒，预示着一年的农事活动即将拉开序幕。',
    threePhenologies: ['东风解冻', '蛰虫始振', '鱼陟负冰'],
    poetry: '阳和启蛰，品物皆春。',
    poetryAuthor: '《无题二首》 唐·李商隐',
    customs: ['咬春（吃春饼、春卷）', '打春（鞭春牛）', '迎春'],
    musicNote: 'C4',
    colorClass: 'border-emerald-500/30 shadow-emerald-500/10',
    textColor: 'text-emerald-400',
  },
  {
    id: 2,
    name: '雨水',
    pinyin: 'Yǔshuǐ',
    english: 'Rain Water',
    season: 'spring',
    longitude: 330,
    dateRange: '2月18日 - 2月20日',
    meaning: '降雪停止，降雨开始，雨量渐增，草木萌动，是润泽万物的重要时节。',
    threePhenologies: ['獭祭鱼', '候雁北', '草木萌动'],
    poetry: '随风潜入夜，润物细无声。',
    poetryAuthor: '《春夜喜雨》 唐·杜甫',
    customs: ['拉保保（认义父）', '撞拜寄', '送雨水'],
    musicNote: 'D4',
    colorClass: 'border-emerald-500/30 shadow-emerald-500/10',
    textColor: 'text-emerald-400',
  },
  {
    id: 3,
    name: '惊蛰',
    pinyin: 'Jīngzhé',
    english: 'Awakening of Insects',
    season: 'spring',
    longitude: 345,
    dateRange: '3月5日 - 3月7日',
    meaning: '春雷始鸣，惊醒蛰伏在泥土中冬眠的各种昆虫与小动物，气温回升明显。',
    threePhenologies: ['桃始华', '仓庚鸣', '鹰化为鸠'],
    poetry: '微雨众卉新，一雷惊蛰始。',
    poetryAuthor: '《观田家》 唐·韦应物',
    customs: ['吃梨', '祭白虎化解是非', '打小人', '蒙鼓皮'],
    musicNote: 'E4',
    colorClass: 'border-emerald-500/30 shadow-emerald-500/10',
    textColor: 'text-emerald-400',
  },
  {
    id: 4,
    name: '春分',
    pinyin: 'Chūnfēn',
    english: 'Vernal Equinox',
    season: 'spring',
    longitude: 0,
    dateRange: '3月20日 - 3月22日',
    meaning: '太阳直射赤道，昼夜平分。此后太阳直射点继续北移，北半球白天渐长。',
    threePhenologies: ['玄鸟至', '雷乃发声', '始电'],
    poetry: '春分麦起身，一刻值千金。',
    poetryAuthor: '《春分古谚》 传统农谚',
    customs: ['立蛋', '吃春菜', '送春贴', '拜神'],
    musicNote: 'G4',
    colorClass: 'border-emerald-500/30 shadow-emerald-500/10',
    textColor: 'text-emerald-400',
  },
  {
    id: 5,
    name: '清明',
    pinyin: 'Qīngmíng',
    english: 'Pure Brightness',
    season: 'spring',
    longitude: 15,
    dateRange: '4月4日 - 4月6日',
    meaning: '气温变暖，草木萌茂，天清地明，空气清新。既是自然节气，也是祭祖节日。',
    threePhenologies: ['桐始华', '田鼠化为鴽', '虹始见'],
    poetry: '清明时节雨纷纷，路上行人欲断魂。',
    poetryAuthor: '《清明》 唐·杜牧',
    customs: ['扫墓祭祖', '踏青折柳', '放风筝', '吃青团'],
    musicNote: 'A4',
    colorClass: 'border-emerald-500/30 shadow-emerald-500/10',
    textColor: 'text-emerald-400',
  },
  {
    id: 6,
    name: '谷雨',
    pinyin: 'Gǔyǔ',
    english: 'Grain Rain',
    season: 'spring',
    longitude: 30,
    dateRange: '4月19日 - 4月21日',
    meaning: '春季的最后一个节气。雨水滋润百谷，秧苗初插，作物新种，最需要雨水灌溉。',
    threePhenologies: ['萍始生', '鸣鸠拂其羽', '戴胜降于桑'],
    poetry: '正好清明连谷雨，一杯香茗暂留客。',
    poetryAuthor: '《谷雨》 清·郑板桥',
    customs: ['走谷雨', '品谷雨茶', '食香椿', '祭海'],
    musicNote: 'C5',
    colorClass: 'border-emerald-500/30 shadow-emerald-500/10',
    textColor: 'text-emerald-400',
  },
  {
    id: 7,
    name: '立夏',
    pinyin: 'Lìxià',
    english: 'Beginning of Summer',
    season: 'summer',
    longitude: 45,
    dateRange: '5月5日 - 5月7日',
    meaning: '夏季开始，万物繁茂，温度明显升高，雷雨增多，农作物进入旺盛生长阶段。',
    threePhenologies: ['蝼蝈鸣', '蚯蚓出', '王瓜生'],
    poetry: '绿树阴浓夏日长，楼台倒影入池塘。',
    poetryAuthor: '《山亭夏日》 唐·高骈',
    customs: ['秤人', '吃立夏蛋', '尝新（尝三新）', '斗蛋'],
    musicNote: 'D4',
    colorClass: 'border-rose-500/30 shadow-rose-500/10',
    textColor: 'text-rose-400',
  },
  {
    id: 8,
    name: '小满',
    pinyin: 'Xiǎomǎn',
    english: 'Grain Buds',
    season: 'summer',
    longitude: 60,
    dateRange: '5月20日 - 5月22日',
    meaning: '夏熟作物的籽粒开始灌浆饱满，但还未完全成熟，故称“小满”。',
    threePhenologies: ['苦菜秀', '靡草死', '麦秋至'],
    poetry: '最是小满景色好，麦浪滚滚迎风笑。',
    poetryAuthor: '《小满行》 传统诗词',
    customs: ['祭车神', '祭蚕神', '抢水', '食苦菜'],
    musicNote: 'E4',
    colorClass: 'border-rose-500/30 shadow-rose-500/10',
    textColor: 'text-rose-400',
  },
  {
    id: 9,
    name: '芒种',
    pinyin: 'Mángzhòng',
    english: 'Grain in Ear',
    season: 'summer',
    longitude: 75,
    dateRange: '6月5日 - 6月7日',
    meaning: '有芒的麦子快收，有芒的稻子可种。是一个忙碌于“夏收、夏种、夏管”的季节。',
    threePhenologies: ['螳螂生', '鵙始鸣', '反舌无声'],
    poetry: '芒种忙忙割，农家乐事多。',
    poetryAuthor: '《观刈麦》 唐·白居易（意引）',
    customs: ['送花神', '安苗', '打泥巴仗', '煮梅'],
    musicNote: 'G4',
    colorClass: 'border-rose-500/30 shadow-rose-500/10',
    textColor: 'text-rose-400',
  },
  {
    id: 10,
    name: '夏至',
    pinyin: 'Xiàzhì',
    english: 'Summer Solstice',
    season: 'summer',
    longitude: 90,
    dateRange: '6月21日 - 6月22日',
    meaning: '太阳直射北回归线，北半球白昼最长，黑夜最短。此后直射点南移，白昼渐短。',
    threePhenologies: ['鹿角解', '蝉始鸣', '半夏生'],
    poetry: '东边日出西边雨，道是无晴却有晴。',
    poetryAuthor: '《竹枝词》 唐·刘禹锡',
    customs: ['吃夏至面', '祭神祖', '消夏避暑'],
    musicNote: 'A4',
    colorClass: 'border-rose-500/30 shadow-rose-500/10',
    textColor: 'text-rose-400',
  },
  {
    id: 11,
    name: '小暑',
    pinyin: 'Xiǎoshǔ',
    english: 'Minor Heat',
    season: 'summer',
    longitude: 105,
    dateRange: '7月6日 - 7月8日',
    meaning: '天气开始炎热，但还未达到最热。伏天即将开始，雨水频繁。',
    threePhenologies: ['温风至', '蟋蟀居壁', '鹰始挚'],
    poetry: '薰风愠解引新凉，小暑蝉鸣稻谷香。',
    poetryAuthor: '《小暑后》 宋·徐玑',
    customs: ['头伏饺子二伏面', '尝新米', '晒衣晒书'],
    musicNote: 'C5',
    colorClass: 'border-rose-500/30 shadow-rose-500/10',
    textColor: 'text-rose-400',
  },
  {
    id: 12,
    name: '大暑',
    pinyin: 'Dàshǔ',
    english: 'Major Heat',
    season: 'summer',
    longitude: 120,
    dateRange: '7月22日 - 7月24日',
    meaning: '一年中最热的时期，正值“中伏”。日照最强，气温最高，喜温作物生长最快。',
    threePhenologies: ['腐草为萤', '土润溽暑', '大雨时行'],
    poetry: '赤日满天地，日光红似火。',
    poetryAuthor: '《夏歌》 唐·李绅',
    customs: ['喝暑羊', '吃仙草', '送大暑船', '饮伏茶'],
    musicNote: 'D5',
    colorClass: 'border-rose-500/30 shadow-rose-500/10',
    textColor: 'text-rose-400',
  },
  {
    id: 13,
    name: '立秋',
    pinyin: 'Lìqiū',
    english: 'Beginning of Autumn',
    season: 'autumn',
    longitude: 135,
    dateRange: '8月7日 - 8月9日',
    meaning: '秋季开始，暑去凉来，万物开始从繁茂走向成熟，秋季作物进入丰收的关键期。',
    threePhenologies: ['凉风至', '白露降', '寒蝉鸣'],
    poetry: '睡起秋声无觅处，满阶梧叶月明中。',
    poetryAuthor: '《立秋》 宋·刘翰',
    customs: ['贴秋膘', '啃秋（吃西瓜）', '晒秋', '摸秋'],
    musicNote: 'C4',
    colorClass: 'border-amber-500/30 shadow-amber-500/10',
    textColor: 'text-amber-400',
  },
  {
    id: 14,
    name: '处暑',
    pinyin: 'Chùshǔ',
    english: 'End of Heat',
    season: 'autumn',
    longitude: 150,
    dateRange: '8月22日 - 8月24日',
    meaning: '“处”含有躲藏、终止之意。表示炎热的暑天即将过去，气温开始逐渐转凉。',
    threePhenologies: ['鹰乃祭鸟', '天地始肃', '禾乃登'],
    poetry: '离离暑云散，袅袅凉风起。',
    poetryAuthor: '《岁晚》 唐·白居易',
    customs: ['出海迎秋（开渔节）', '祭祖迎秋', '吃鸭子', '放河灯'],
    musicNote: 'D4',
    colorClass: 'border-amber-500/30 shadow-amber-500/10',
    textColor: 'text-amber-400',
  },
  {
    id: 15,
    name: '白露',
    pinyin: 'Báilù',
    english: 'White Dew',
    season: 'autumn',
    longitude: 165,
    dateRange: '9月7日 - 9月9日',
    meaning: '天气渐凉，夜间空气中的水汽在草木上凝结成白色的露珠，清晨尤为明显。',
    threePhenologies: ['鸿雁来', '玄鸟归', '群鸟养羞'],
    poetry: '露从今夜白，月是故乡明。',
    poetryAuthor: '《月夜忆舍弟》 唐·杜甫',
    customs: ['收清露', '饮白露茶', '吃龙眼', '喝白露米酒'],
    musicNote: 'E4',
    colorClass: 'border-amber-500/30 shadow-amber-500/10',
    textColor: 'text-amber-400',
  },
  {
    id: 16,
    name: '秋分',
    pinyin: 'Qiūfēn',
    english: 'Autumnal Equinox',
    season: 'autumn',
    longitude: 180,
    dateRange: '9月22日 - 9月24日',
    meaning: '太阳第二次直射赤道，昼夜再次平分。自此之后，阳光直射位置南移，北半球夜渐长。',
    threePhenologies: ['雷始收声', '蛰虫坯户', '水始涸'],
    poetry: '金气秋分，风清露冷。',
    poetryAuthor: '《秋分词》 传统古诗',
    customs: ['祭月', '吃秋菜', '送秋牛', '粘雀子嘴'],
    musicNote: 'G4',
    colorClass: 'border-amber-500/30 shadow-amber-500/10',
    textColor: 'text-amber-400',
  },
  {
    id: 17,
    name: '寒露',
    pinyin: 'Hánlù',
    english: 'Cold Dew',
    season: 'autumn',
    longitude: 195,
    dateRange: '10月7日 - 10月9日',
    meaning: '露水比白露时更冷，快要凝结成霜。气温更低，秋熟作物正进入收割期。',
    threePhenologies: ['鸿雁来宾', '雀入大水为蛤', '菊有黄华'],
    poetry: '寒露惊秋晚，朝看菊渐黄。',
    poetryAuthor: '《授衣》 唐·元稹',
    customs: ['登高赏秋', '赏菊喝菊花酒', '吃芝麻', '钓秋鱼'],
    musicNote: 'A4',
    colorClass: 'border-amber-500/30 shadow-amber-500/10',
    textColor: 'text-amber-400',
  },
  {
    id: 18,
    name: '霜降',
    pinyin: 'Shuāngjiàng',
    english: 'Frost\'s Descent',
    season: 'autumn',
    longitude: 210,
    dateRange: '10月23日 - 10月24日',
    meaning: '秋季的最后一个节气。天气渐冷，开始有霜，大自然呈现一片深秋的景象。',
    threePhenologies: ['豺乃祭兽', '草木黄落', '蛰虫咸俯'],
    poetry: '霜叶红于二月花。',
    poetryAuthor: '《山行》 唐·杜牧',
    customs: ['吃柿子', '登高远眺', '赏菊饮酒', '扫墓'],
    musicNote: 'C5',
    colorClass: 'border-amber-500/30 shadow-amber-500/10',
    textColor: 'text-amber-400',
  },
  {
    id: 19,
    name: '立冬',
    pinyin: 'Lìdōng',
    english: 'Beginning of Winter',
    season: 'winter',
    longitude: 225,
    dateRange: '11月7日 - 11月8日',
    meaning: '冬季开始，万物收藏，规避寒冷。此时作物收割完毕，开始封仓入库。',
    threePhenologies: ['水始冰', '地始冻', '雉入大水为蜃'],
    poetry: '细雨生寒未有霜，庭前木叶半青黄。',
    poetryAuthor: '《立冬》 宋·仇远',
    customs: ['吃饺子（北方）', '补冬（南方）', '祭冬祖'],
    musicNote: 'C4',
    colorClass: 'border-sky-500/30 shadow-sky-500/10',
    textColor: 'text-sky-400',
  },
  {
    id: 20,
    name: '小雪',
    pinyin: 'Xiǎoxuě',
    english: 'Light Snow',
    season: 'winter',
    longitude: 240,
    dateRange: '11月22日 - 11月23日',
    meaning: '气温下降，开始降雪，但由于雪量还小，地面上还未产生较厚的积雪。',
    threePhenologies: ['虹藏不见', '天气上升地气下降', '闭塞而成冬'],
    poetry: '小雪辟寒气，新炉煮晚茶。',
    poetryAuthor: '《夜雨》 传统诗歌（意引）',
    customs: ['腌腊肉腊肠', '吃糍粑', '晒鱼干'],
    musicNote: 'D4',
    colorClass: 'border-sky-500/30 shadow-sky-500/10',
    textColor: 'text-sky-400',
  },
  {
    id: 21,
    name: '大雪',
    pinyin: 'Dàxuě',
    english: 'Heavy Snow',
    season: 'winter',
    longitude: 255,
    dateRange: '12月6日 - 12月8日',
    meaning: '降雪范围更广，雪量增多，地面积雪加深，天气寒冷，开始进入“数九”伏天前夕。',
    threePhenologies: ['鶡鴠不鸣', '虎始交', '荔挺出'],
    poetry: '忽如一夜春风来，千树万树梨花开。',
    poetryAuthor: '《白雪歌送武判官归京》 唐·岑参',
    customs: ['吃红薯粥', '观赏冰雪', '捕鱼赏雪'],
    musicNote: 'E4',
    colorClass: 'border-sky-500/30 shadow-sky-500/10',
    textColor: 'text-sky-400',
  },
  {
    id: 22,
    name: '冬至',
    pinyin: 'Dōngzhì',
    english: 'Winter Solstice',
    season: 'winter',
    longitude: 270,
    dateRange: '12月21日 - 12月23日',
    meaning: '太阳直射南回归线，北半球白昼最短，黑夜最长。这一天俗称“冬节”，标志着最寒冷的“数九寒天”到来。',
    threePhenologies: ['蚯蚓结', '麋角解', '水泉动'],
    poetry: '天时人事日相催，冬至阳生春又来。',
    poetryAuthor: '《小至》 唐·杜甫',
    customs: ['吃饺子（北方）', '吃汤圆（南方）', '祭天祭祖', '画九九消寒图'],
    musicNote: 'G4',
    colorClass: 'border-sky-500/30 shadow-sky-500/10',
    textColor: 'text-sky-400',
  },
  {
    id: 23,
    name: '小寒',
    pinyin: 'Xiǎohán',
    english: 'Minor Cold',
    season: 'winter',
    longitude: 285,
    dateRange: '1月5日 - 1月7日',
    meaning: '标志着一年中最寒冷的时间（“三九”天）到来。虽然叫小寒，但很多地区小寒甚至比大寒更冷。',
    threePhenologies: ['雁北乡', '鹊始巢', '雉始雊'],
    poetry: '小寒连大寒，收拾准备过新年。',
    poetryAuthor: '《岁首谣》 民间俗语',
    customs: ['吃腊八粥', '吃糯米饭', '探梅'],
    musicNote: 'A4',
    colorClass: 'border-sky-500/30 shadow-sky-500/10',
    textColor: 'text-sky-400',
  },
  {
    id: 24,
    name: '大寒',
    pinyin: 'Dàhán',
    english: 'Major Cold',
    season: 'winter',
    longitude: 300,
    dateRange: '1月20日 - 1月21日',
    meaning: '二十四节气中的最后一个节气。极度寒冷，正值四九，民俗中充满着除旧迎新、迎祥纳福的年味。',
    threePhenologies: ['鸡乳', '征鸟厉疾', '水泽腹坚'],
    poetry: '大寒迎年忙，岁末合家欢。',
    poetryAuthor: '《大寒吟》 传统歌谣',
    customs: ['尾牙祭', '除尘迎年', '制腊味', '买芝麻秸'],
    musicNote: 'C5',
    colorClass: 'border-sky-500/30 shadow-sky-500/10',
    textColor: 'text-sky-400',
  },
];

export const MANSIONS = {
  east: {
    name: '东方苍龙',
    color: '#10b981', // emerald
    stars: ['角', '亢', '氐', '房', '心', '尾', '箕'],
    angles: [0, 13, 23, 38, 43, 50, 68], // relative angles
  },
  north: {
    name: '北方玄武',
    color: '#38bdf8', // sky
    stars: ['斗', '牛', '女', '虚', '危', '室', '壁'],
    angles: [90, 112, 120, 128, 138, 158, 175],
  },
  west: {
    name: '西方白虎',
    color: '#e2e8f0', // slate white
    stars: ['奎', '娄', '胃', '昴', '毕', '觜', '参'],
    angles: [180, 196, 206, 221, 232, 248, 250],
  },
  south: {
    name: '南方朱雀',
    color: '#f43f5e', // rose
    stars: ['井', '鬼', '柳', '星', '张', '翼', '轸'],
    angles: [270, 303, 308, 323, 330, 348, 354],
  },
};

export const MUSIC_PRESETS: MusicPreset[] = [
  {
    id: 'ganshan',
    name: '高山流水',
    description: '意境空灵清幽。背景是极为缓慢悠远的古琴余音，主旋律则是清澈流动的山泉律动。',
    scale: '宫调式 (C Major Pentatonic)',
    code: `// 《高山流水》 - 宫调式 (C Major Pentatonic)
// 空灵的古琴余音与高山流水的律动
stack(
  // 古琴长音 (背景)
  note("c3 e3 g3 a3 c4").s("sine").slow(4).gain(0.55),
  // 流水叮咚 (主旋律)
  note("c4 d4 e4 g4 a4 g4 e4 d4").s("triangle").slow(2).gain(0.75),
  // 幽谷清泉 (高音点缀)
  note("e5 g5 a5 c6").s("sine").slow(3).gain(0.45)
)`,
  },
  {
    id: 'chunjiang',
    name: '春江花月夜',
    description: '描绘江南春江潮水与一轮明月的静谧之美。柔美的商调律动，层层铺开，韵味绵长。',
    scale: '商调式 (D Pentatonic)',
    code: `// 《春江花月夜》 - 商调式 (D Pentatonic)
// 描绘江南春江潮水与一轮明月的静谧之美
stack(
  // 潮水涌动 (低音背景)
  note("d3 g3 a3 d4").s("sine").slow(5).gain(0.5),
  // 琵琶清拨 (中音主旋律)
  note("d4 e4 g4 a4 c5 a4 g4 e4").s("triangle").slow(1.5).gain(0.8),
  // 箫笛悠扬 (高音旋律)
  note("d5 [e5 g5] a5 [g5 e5] d5").s("sine").slow(2.5).gain(0.65)
)`,
  },
  {
    id: 'hanshan',
    name: '寒山钟声',
    description: '取材自“姑苏城外寒山寺，夜半钟声到客船”。钟声浑厚，意境清冷孤绝，饱含禅意。',
    scale: '徵调式 (G Pentatonic)',
    code: `// 《寒山钟声》 - 徵调式 (G Pentatonic)
// 姑苏城外寒山寺，夜半钟声到客船
stack(
  // 寒山晚钟 (浑厚低音)
  note("g2 d3 g3").s("sine").slow(8).gain(0.9),
  // 禅意余音 (飘渺氛围)
  note("g4 b4 c5 d5 b4 g4").s("sine").slow(3).gain(0.45),
  // 孤舟客船 (偶尔的高音)
  note("d5 [g5 a5] d6").s("triangle").slow(4).gain(0.5)
)`,
  },
  {
    id: 'nichang',
    name: '霓裳羽衣',
    description: '唐代宫廷仙乐。以羽调式铺展出云雾缭绕之感，清脆的高音如霓裳飘飘、玉盘落珠。',
    scale: '羽调式 (A Pentatonic)',
    code: `// 《霓裳羽衣》 - 羽调式 (A Pentatonic)
// 唐代宫廷仙乐，空灵虚幻，如登羽仙
stack(
  // 仙乐背景 (弦乐铺底)
  note("a3 e4 a4 b4 c5").s("sine").slow(3).gain(0.6),
  // 玉盘落珠 (灵动音符)
  note("a4 c5 e5 a5 g5 e5 c5 b4").s("triangle").slow(1.2).gain(0.75),
  // 霓裳飘飘 (高空风铃)
  note("e5 g5 a5 b5 c6 e6").s("sine").slow(2.4).gain(0.5)
)`,
  },
];
